# Generated by Django 6.0.6 on 2026-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
